version: '3.7'

services:
    web:
        build: .
        ports:
            - "5000:5000"
        environment:
            OPENEXCHANGE_APP_ID: "{YOUR_OPENEXCHANGE_APP_ID_COMES_HERE}"
            MONGO_HOST: "mongodb"
            MONGO_USERNAME: "username"
            MONGO_PASSWORD: "password"
            UPDATE_CURRENCIES_MINUTES_SCHEDULE: "10"
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: currency
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
