name: CI
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.10.6]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
              
      - name:  Set up Python 3.10.6
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.6"
          cache: "pip"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Run unit tests
        run: python -m pytest
          
